/**
 * 牌桌外觀的文案表。這一份同時也是 TextKey 的來源 ——
 * 其他外觀的 text 必須是同一組 key，缺一個編譯就會擋下來。
 *
 * 值裡的 {name} 會被 t() 的第二個參數代換。
 */
export const CASINO_TEXT = {
  // 進入畫面
  'gate.title': '線上牌桌',
  'gate.titleAccent': 'Online',
  'gate.subtitle': '大老二 2~4 人、德州撲克 2~9 人、大富翁 2~6 人，可開房、加入、觀戰',
  'gate.nicknamePlaceholder': '輸入暱稱',
  'gate.submit': '開始',

  'toast.failed': '操作失敗',

  // 大廳
  'lobby.nicknameLabel': '暱稱',
  'lobby.rename': '更名',
  'lobby.connected': '已連線',
  'lobby.connecting': '連線中…',
  'lobby.createTitle': '建立房間',
  'lobby.roomNamePlaceholder': '{name} 的房間',
  'lobby.gameTypeLabel': '玩法',
  'lobby.rulesLabel': '規則',
  'lobby.rulesOptionsLabel': '規則細項',
  'lobby.maxPlayersLabel': '人數上限',
  'lobby.seatOption': '{n} 人',
  'lobby.create': '開房',
  'lobby.codeTitle': '用房號加入',
  'lobby.codePlaceholder': '例如 K7QM',
  'lobby.join': '加入',
  'lobby.listTitle': '房間列表（{n}）',
  'lobby.empty': '目前沒有房間，開一間吧。',
  'lobby.host': '房主 {name}',
  'lobby.playerCount': '{n}/{max} 人',
  'lobby.playerNpcCount': '{human} 人 + {npc} 電腦／{max}',
  'lobby.spectatorCount': '觀戰 {n}',
  'lobby.started': '這局已開打',
  'lobby.full': '房間已滿',
  'lobby.requestJoin': '申請加入',
  'lobby.requestJoinSent': '已送出申請，等房主同意',
  'lobby.spectate': '觀戰',
  'lobby.status.waiting': '等待中',
  'lobby.status.playing': '遊戲中',
  'lobby.status.finished': '已結束',

  // 房間外框
  'room.code': '房號 #{id}',
  'room.spectating': '觀戰中',
  'room.sitDown': '坐下來玩',
  'room.toSpectator': '改為觀戰',
  'room.leave': '離開房間',
  'room.emptySeat': '空位',
  'room.godView': '上帝視角',
  'room.turnTag': '輪到',
  'room.spectators': '觀戰者（{n}）',
  'room.chatTitle': '房間聊天',
  'room.turnPrefix': '輪到',
  'room.turnMine': '輪到你了',

  // 聊天
  'chat.lobbyTitle': '大廳聊天',
  'chat.empty': '還沒有人說話',
  'chat.placeholder': '說點什麼…',
  'chat.send': '送出',

  // 座位
  'seat.you': '你',
  'seat.host': '房主',
  'seat.offline': '斷線',
  'seat.button': 'D',
  'seat.sb': 'SB',
  'seat.bb': 'BB',
  'seat.pass': 'PASS',
  'seat.ready': '已準備',
  'seat.notReady': '未準備',
  'seat.rank': '{medal} 第 {n} 名',
  'seat.chips': '🪙 {n}',
  'seat.sitOut': '坐出',
  'seat.allIn': 'ALL-IN',
  'seat.bet': '下注 {n}',
  'seat.left': '(已離開)',

  // 牌
  'card.backTitle': '剩 {n} 張',

  // 開局
  'start.ready': '準備',
  'start.cancelReady': '取消準備',
  'start.startBigTwo': '開始遊戲',
  'start.startHoldem': '開始牌局',
  'start.startMonopoly': '開始遊戲',
  'start.startTaiwanMahjong': '開始遊戲',
  'start.needPlayers': '需要至少 {min} 人，且所有人都已準備',

  // 大老二
  'bigTwo.idleTitle': '等待房主開始遊戲',
  'bigTwo.idleHint': '目前 {n}/{max} 人，至少 {min} 人可開始',
  'bigTwo.lastPlay': '{name} 的 {combo}',
  'bigTwo.freeLead': '自由出牌',
  'bigTwo.mustIncludeOpening': ' · 這一手必須包含開局牌',
  'bigTwo.resultTitle': '本局結束',
  'bigTwo.playAgain': '再來一局',
  'bigTwo.waitHost': '等房主開下一局',
  'bigTwo.play': '出牌',
  'bigTwo.pass': 'PASS',
  'bigTwo.suggest': '提示',
  'bigTwo.cannotPass': '你有領牌權，不能 PASS',
  'bigTwo.sortRank': '排序：按大小',
  'bigTwo.sortSuit': '排序：按花色',
  'bigTwo.suitOrder': '花色大小',
  'bigTwo.handEmpty': '手牌已出完',
  'bigTwo.waitingDeal': '等待發牌',
  'hint.notPlaying': '按下準備，等房主開局',
  'hint.waitOthers': '等待其他玩家出牌',
  'hint.selectToFollow': '請選 {n} 張牌跟牌',
  'hint.selectCards': '請選擇要出的牌',
  'hint.invalidCombo': '這不是合法的牌型',
  'hint.mustIncludeOpening': '第一手必須包含開局牌',
  'hint.mustPlayN': '必須出 {n} 張',
  'hint.mustMatchCombo': '這一輪只能用{combo}跟',
  'hint.noFlush': '這一局不能出同花',
  'hint.cannotBeat': '{combo} 壓不過上一手',
  'hint.canPlay': '可出：{combo}',
  'hint.canCut': '切！{combo}',

  // 德州撲克
  'holdem.idleTitle': '等待房主開始牌局',
  'holdem.idleHint': '目前 {n}/{max} 人，至少 {min} 人可開始',
  'holdem.handNo': '第 {n} 手',
  'holdem.blinds': '盲注 {sb}/{bb}',
  'holdem.pot': '底池 {n}',
  'holdem.mainPot': '主池 {n}',
  'holdem.sidePot': '邊池 {i} {n}',
  'holdem.currentBet': '目前注額 {n}',
  'holdem.showdownTitle': '第 {n} 手結束',
  'holdem.nextHandSoon': '稍後自動發下一手',
  'holdem.fold': '蓋牌',
  'holdem.check': '過牌',
  'holdem.call': '跟注 {n}',
  'holdem.raiseTo': '加注到 {n}',
  'holdem.allIn': 'All-in',
  'holdem.raiseAmountLabel': '加注金額',
  'holdem.raiseToLabel': '加注到',
  'holdem.myCommitted': '本街已下注 {n}',
  'holdem.strength': '目前：{hand}',
  'holdem.noCards': '這一手沒有你的牌',
  'holdemHint.notStarted': '按下準備，等房主開局',
  'holdemHint.handOver': '這一手結束了，稍後自動發下一手',
  'holdemHint.waitStart': '等待開局',
  'holdemHint.waitOthers': '等待其他玩家下注',
  'holdemHint.notInHand': '你這一手沒有參與',
  'holdemHint.canCheck': '可以過牌，或加注到 {n} 以上',
  'holdemHint.mustCall': '要跟 {n} 才能繼續',
  'holdemHint.yourTurn': '輪到你了',

  // 大富翁
  'monopoly.idleTitle': '等待房主開始遊戲',
  'monopoly.idleHint': '目前 {n}/{max} 人，至少 {min} 人可開始',
  'monopoly.round': '第 {n} 巡',
  'monopoly.phase': '階段：{phase}',
  'monopoly.dice': '骰子 {a} + {b} = {n}',
  'monopoly.noDice': '尚未擲骰',
  'monopoly.activePlayer': '{name} 的回合',
  'monopoly.cash': '現金 {n}',
  'monopoly.netWorth': '身家 {n}',
  'monopoly.parkingPot': '獎金池 {n}',
  'monopoly.supply': '銀行：房 {houses}／飯店 {hotels}',
  'monopoly.jailTag': '獄中',
  'monopoly.jailTurns': '獄中第 {n} 巡',
  'monopoly.jailCards': '出獄卡 {n}',
  'monopoly.bankruptTag': '破產',
  'monopoly.boardTitle': '棋盤',
  'monopoly.here': '你在這裡',
  'monopoly.mine': '你的',
  'monopoly.ownerless': '無主',
  'monopoly.mortgagedTag': '抵押中',
  'monopoly.price': '價 {n}',
  'monopoly.rent': '租 {n}',
  'monopoly.roll': '擲骰',
  'monopoly.buy': '買下（{n}）',
  'monopoly.decline': '不買',
  'monopoly.bid': '出價',
  'monopoly.bidAmountLabel': '出價金額',
  'monopoly.passBid': '不加價',
  'monopoly.auctionTitle': '拍賣：{tile}',
  'monopoly.auctionHigh': '目前最高 {n}（{name}）',
  'monopoly.auctionNoBid': '目前沒有人出價',
  'monopoly.payBail': '交保（{n}）',
  'monopoly.useJailCard': '用出獄卡',
  'monopoly.rollForDoubles': '擲同點出獄',
  'monopoly.build': '蓋房',
  'monopoly.sellHouse': '拆房',
  'monopoly.mortgage': '抵押',
  'monopoly.unmortgage': '贖回',
  'monopoly.endTurn': '結束回合',
  'monopoly.offerTrade': '提出交易',
  'monopoly.cancelTrade': '取消',
  'monopoly.declareBankrupt': '宣告破產',
  'monopoly.debtTitle': '欠 {name} {n}',
  'monopoly.debtToBank': '欠銀行 {n}',
  'monopoly.debtShortfall': '還差 {n}，最多能變現 {max}',
  'monopoly.tradeTitle': '{name} 想跟你交易',
  'monopoly.tradeGive': '他給',
  'monopoly.tradeWant': '他要',
  'monopoly.tradeAccept': '接受',
  'monopoly.tradeReject': '拒絕',
  'monopoly.tradeTarget': '交易對象',
  'monopoly.tradeCashLabel': '附加現金',
  'monopoly.tradeNothing': '（沒有地產）',
  'monopoly.resultTitle': '本局結束',
  'monopoly.resultReason': '結束原因：{reason}',
  'monopoly.playAgain': '再來一局',
  'monopoly.waitHost': '等房主開下一局',
  'monopoly.myEstates': '我的地產（{n}）',
  'monopoly.noEstates': '還沒有任何地產',
  'monopolyHint.notPlaying': '按下準備，等房主開局',
  'monopolyHint.waitOthers': '等待其他玩家',
  'monopolyHint.yourTurn': '輪到你了',
  'monopolyHint.spectating': '觀戰中',

  // 台灣麻將
  'mahjong.idleTitle': '等待房主開始遊戲',
  'mahjong.idleHint': '固定 4 人，目前 {n}/{max} 人',
  'mahjong.round': '第 {n} 局',
  'mahjong.banker': '莊家 {name}',
  'mahjong.wall': '牌牆 {n}',
  'mahjong.discard': '出牌',
  'mahjong.hu': '胡',
  'mahjong.gang': '槓',
  'mahjong.peng': '碰',
  'mahjong.chi': '吃',
  'mahjong.pass': '過',
  'mahjong.none': '不動作',
  'mahjong.lastDiscard': '{name} 打出 {tile}',
  'mahjong.selfDrawTitle': '自摸了，要不要動作？',
  'mahjong.reactionTitle': '{name} 打出了 {tile}',
  'mahjong.resultTitle': '本局結束',
  'mahjong.winSelfDraw': '{name} 自摸，{n} 台',
  'mahjong.winDiscard': '{name} 胡牌，{n} 台',
  'mahjong.drawResult': '流局，莊家連莊',
  'mahjong.nextRoundSoon': '等所有人按下「繼續」才會開下一局，逾時 20 秒會直接開下一局',
  'mahjong.revealedHandsTitle': '公開牌組',
  'mahjong.joinRequestText': '{name} 想要加入這場牌局，頂替一個電腦座位',
  'mahjong.joinRequestAccept': '接受',
  'mahjong.joinRequestReject': '婉拒',
  'mahjong.winningHandLabel': '胡牌牌型',
  'mahjong.readyContinue': '繼續下一局',
  'mahjong.readyWaiting': '等待其他人…',
  'mahjong.readyCount': '{n} / 4 人已確認',
  'mahjong.matchOverTitle': '整場比賽結束',
  'mahjong.matchWinner': '獲勝者：{name}',
  'mahjong.playAgain': '再來一局',
  'mahjong.waitHost': '等房主開下一局',
  'mahjong.scoreLabel': '{n} 分',
  'mahjong.myScoreLabel': '我的分數：{n}',
  'mahjong.flowerCount': '花 {n}',
  'mahjong.handEmpty': '等待發牌',
  'mahjong.dealerTag': '莊',
  'mahjong.addNpc': '補電腦玩家',
  'mahjong.bankerDiceResult': '{name} 是這場比賽的莊家！',
  'mahjong.dealing': '發牌中…',
  'mahjong.gameStartBanner': '遊戲開始！',
  'mahjongHint.notPlaying': '按下準備，等房主開局（固定 4 人）',
  'mahjongHint.waitOthers': '等待其他玩家',
  'mahjongHint.yourTurnDiscard': '輪到你出牌',
  'mahjongHint.selfDraw': '自摸了，選擇要不要胡或槓',
  'mahjongHint.reaction': '可以選擇吃／碰／槓／胡，或過',
  'mahjongHint.roundEnd': '這一局結束了，稍後自動開下一局',
} as const;

export type TextKey = keyof typeof CASINO_TEXT;

export type TextTable = Record<TextKey, string>;
